image: ruby:2.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
  paths:
    - vendor

before_script:
  - bundle install

build:
  stage: build
  script:
  - bundle exec jekyll build
  artifacts:
    paths:
    - _site

